### ISSUE TITLE
migrate successfull but artisan has error

### ISSUE THREAD

**Issue by Egonyu** [Hardeepcoder/LaraBook-Social-Network-in-laravel-5.4#1]
[PDOException]
  SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was t
  oo long; max key length is 767 bytes

this is an amazing project i learn alot from it 
tahnks hardeepcoder

**Comment by Hardeepcoder** [comment]
please check this video i explained whole: [Video!] (https://www.youtube.com/watch?v=Qm_tjqBHuDU)

**Comment by daniels123kid** [comment]
thanks alot ur my mentor

**Comment by daniels123kid** [comment]
hey am sorry again am running into a nother error related to the above issue i earlier asked you about and here is the error msge:
i have already included the following on appServiceProviders in the app directory,
use illuminate\Support\Facades\Schema;
and 
Schema::defaultStringLength(191);
PS C:\xampp\htdocs\LaraBook> php artisan migrate
Migration table created successfully.

  [Illuminate\Database\QueryException]

  SQLSTATE[42000]: Syntax error or access violation: 1075 Incorrect table definition; there can be only one auto column and it must be defined as a key (SQL: create table `notifcations` (`id` int unsigned not null auto_increment primary key, `user_logged` int unsigned not null auto_increment primary key, `user_hero` int unsigned not null auto
  _increment primary key, `note` varchar(191) not null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate utf8mb4_unicode_ci)

  [PDOException]
  SQLSTATE[42000]: Syntax error or access violation: 1075 Incorrect table definition; there can be only one auto column and it must be defined as a key

**Comment by Hardeepcoder** [comment]
can u come on my fb page with screenshots ?

**Comment by daniels123kid** [comment]
ok let me get to you
