### ISSUE TITLE
server.php

### ISSUE THREAD

**Issue by Zohaib42** [Hardeepcoder/LaraBook-Social-Network-in-laravel-5.4#2]
Unknown: Failed opening required 'C:\wamp\www\chat/server.php' (include_path='C:\xampp\php\PEAR') in Unknown on line 0

**Comment by aysnet1** [comment]
add file

>  "server.php" 

in your project file   C:\wamp\www\chat--> 

`<?php

/**
 * Laravel - A PHP Framework For Web Artisans
 *
 * @package  Laravel
 * @author   Taylor Otwell <taylorotwell@gmail.com>
 */

$uri = urldecode(
    parse_url($_SERVER['REQUEST_URI'], PHP_URL_PATH)
);

// This file allows us to emulate Apache's "mod_rewrite" functionality from the
// built-in PHP web server. This provides a convenient way to test a Laravel
// application without having installed a "real" web server software here.
if ($uri !== '/' && file_exists(__DIR__.'/public'.$uri)) {
    return false;
}

require_once __DIR__.'/public/index.php';
`
