### ISSUE TITLE
Hi sir i am getting this error kinldy help. thanks

### ISSUE THREAD

**Issue by Tehsseen** [Hardeepcoder/LaraBook-Social-Network-in-laravel-5.4#3]
Warning: require(C:\xampp\htdocs\LaraBook\bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in C:\xampp\htdocs\LaraBook\bootstrap\autoload.php on line 17

Fatal error: require(): Failed opening required 'C:\xampp\htdocs\LaraBook\bootstrap/../vendor/autoload.php' (include_path='C:\xampp\php\PEAR') in C:\xampp\htdocs\LaraBook\bootstrap\autoload.php on line 17

**Comment by Hardeepcoder** [comment]
just run command 

> **composer update**
